### ISSUE TITLE
(False Report) This contains a dangerous malware.

### ISSUE THREAD

**Issue by Slaymaa** [NotTsunami/ShowDeathCause#11]
Showdeathcause.dll installs two instances of Trojan.Coinminer as of 22/08/2022. Avoid this mod at all cost. 
(Analyses through MalwareBytes, Kaspersky, Spyhunter)

**Comment by NotTsunami** [comment]
> Showdeathcause.dll installs two instances of Trojan.Coinminer as of 22/08/2022. Avoid this mod at all cost. (Analyses through MalwareBytes, Kaspersky, Spyhunter)

This is interesting because the full source is located in this repository, and the build on Thunderstore is directly compiled from the source here. On top of that, there hasn't been an update to it since March. When built, it also builds as `ShowDeathCause.dll` and not `Showdeathcause.dll`. Did you download the DLL from [Thunderstore](https://thunderstore.io/package/NotTsunami/ShowDeathCause/) or somewhere else? The mod is pretty popular so I would imagine it has been reuploaded to other sources as well, but I can't guarantee the legitimacy of those because the only one that I build and manage is the one on Thunderstore.

@Slaymaa Can you give any more information on this?

**Comment by NotTsunami** [comment]
Hi, I'm going to close this as a false report. The version uploaded to Thunderstore [reports no trojans](https://www.virustotal.com/gui/file/c7b78d89c4097dc0414b0527e21c21c2ea1f3e87292147cc828e69457c273156/detection) and there has not been any changes since then. If you are downloading mods anywhere else other than Thunderstore, you are downloading them at your own risk and I am not responsible for anything you may run into. I only directly manage the version uploaded to Thunderstore.

I don't appreciate misinformation at all, especially against a mod that is decently large in the community. What I can take accountability and apologize for is the lack of updates. I know there are two fairly important bugs that are still open, and I do apologize for the lack of addressing those. I have been working full-time for a few months now and haven't even touched Risk of Rain since the last update to ShowDeathCause. I cannot promise any ETA for the next update, but I **will** be revisiting the bugs in my free time and will release an update _soon_.
