### ISSUE TITLE
[Bug] Forgive Me Please Equipment

### ISSUE THREAD

**Issue by Kigoria** [NotTsunami/ShowDeathCause#7]
The Forgive Me Please Equipment seems to pulse at much faster speeds than once per second,
leading to low frame rates when coupled with items such as Bandolier.

- Tested by disabling all other mods than important ones such as BepIn, HookGenPatcher and R2API

**Comment by NotTsunami** [comment]
I'm testing this locally and it seems to tick at the regular interval. Forgive Me Please does not proc `OnCharacterDeath`, so the root cause _shouldn't_ be ShowDeathCause, If you are able to find a sureshot way to reproduce this or provide a video, maybe that could help, but I don't think the cause lies with ShowDeathCause.

**Comment by Kigoria** [comment]
The bug seems to be fixed at 3.0.1, i was able to recreate the bug at the 3.0.0 version, but it ticks correctly at the 3.0.1 version

- I started a run with command relic, get to the closest equipment barrel and selected Forgive Me Please

**Comment by NotTsunami** [comment]
Sounds good. If you encounter it again feel free to reopen!
